### ISSUE TITLE
no-unused-var with function variable

### ISSUE THREAD

**Issue by EricBeReal** [ezhlobo/eslint-plugin-react-pug#2]
This plugin is an answer to our prayers!

Having one issue with calling functions declared outside of the template returning the no-unused-var error.  
For instance, the following stateless component:

`
export default function SampleFile(){
  const scopeFunction= link =>  e  => {
    e.preventDefault();
    window.location.href = link;
  };

  return pug`
    button(
      onClick='scopeFunction('/')'
    )
      | Scope Function
  `;
}
`
Returns:
`
2:9  error  'scopeFunction' is assigned a value but never used  no-unused-vars
`

**Comment by ezhlobo** [comment]
@EricBeReal thank you, great catch!

Easily reproduced that issue with following component:

```jsx
const Comp = () => {
  const scopeFunction = link => (e) => {
    e.preventDefault()
    window.location.href = link;
  }

  return pug`
    button(
      onClick=scopeFunction('aaa')
    )
      | Scope Function
  `
}
```

I'll push the fix soon.

**Comment by ezhlobo** [comment]
Version v0.0.3 is published with fix of that issue.

@EricBeReal could you confirm?

**Comment by EricBeReal** [comment]
unfortunately v0.0.3 I'm experiencing the same behaviour

**Comment by ezhlobo** [comment]
@EricBeReal do you pass string to `onClick` or it's a typo?

**Comment by EricBeReal** [comment]
@ezhlobo you're absolutely right.  It passed without the typo.  issue resolved!

**Comment by ezhlobo** [comment]
@EricBeReal great! Thank you again!
