### ISSUE TITLE
It requires to have empty lines between siblings

### ISSUE THREAD

**Issue by Arteaga71** [ezhlobo/eslint-plugin-react-pug#41]
I got the next messages on the following code (below the first button and above the second one):
```
Button(href="#" color="dark" size="sm") Sign In
| &#32;
Button(href="#" color="primary" size="sm") Join now
```

```
error  Need empty line for more than two siblings  react-pug/empty-lines
error  Need empty line for more than two siblings  react-pug/empty-lines
```

**Comment by ezhlobo** [comment]
@Arteaga71 what behavior do you expect?

**Comment by ezhlobo** [comment]
We don't require empty lines around text-only lines. Within [v0.5.2](https://github.com/ezhlobo/eslint-plugin-react-pug/releases/tag/v0.5.2).
