### ISSUE TITLE
repost : pug is undefined no-undef (already tried existing issues related to this)

### ISSUE THREAD

**Issue by zami45** [ezhlobo/eslint-plugin-react-pug#63]
Sorry that I had to post an issue which has already been posted several times here.I have seen the other issues related to this, and i tried almost all the solutions provided to those issues. This is what I have done so far : 

1. Created a new react app using "create-react-app"

2. eject the app using "npm run eject"

3. install  [https://github.com/pugjs/babel-plugin-transform-react-pug](babel-plugin-transform-react-pug ). Added a .babelrc file in root director and added the following to .babelrc file :

```
{
    "plugins": [
      "transform-react-pug",
      "transform-react-jsx"
    ]
}
```
4. installed [https://github.com/ezhlobo/eslint-plugin-react-pug](eslint-plugin-react-pug)  from the github documentation  and created a .eslintrc file and added the following to the .eslintrc file 

```
{
    "plugins": [
        "react-pug"
    ],
    "extends": [
        "plugin:react-pug/all"
    ],
    "globals": {
        "pug": "readonly"

    }
}
```
5. In App.js I added the following simple pug code 

```
import React from 'react';
class App extends React.Component {
  render() {
    return pug`
      div
        h1 My Component
        p This is my component using pug.
    `;
  }
}
export default App;
```
6. After that I've uninstalled the node-modules and re-installed it. And then run npm-start. But no matter what I am getting "pug is undefined no-undef" error message in the compiler.

What went wrong here ?

**Comment by zami45** [comment]
I was able to make it work. You can check it out [here](https://stackoverflow.com/questions/56513346/how-to-use-pug-templating-engine-with-reactjs)

**Comment by ezhlobo** [comment]
@zami45 your solution is actually right ;). If you have any ideas how we can make it more clear here in documentation for other people, let me know.
